openapi: 3.0.1
info:
  title: Col-OTP tibco
  description: "<hr/> API Rest, generate and validate number OTP <br/> For ESB-Tibco\
    \ systems <br/> Low Risk test. <br/>Used Packages: <br/>Schema = xx, PackageDataBase\
    \ = xx, NameOperation = xxx <hr/> Controles de cambio. <br/>\n19/05/2020 - Creació\
    n.<br/> "
  license:
    name: BNP Paribas Cardif Colombia - Seguros Generales S.A
    url: https://bnpparibascardif.com.co/
  version: 1.0.4
servers:
- url: https://vip-busintco-test.co.xcd.net.intra:20310/otp/v1
security:
- name: []
paths:
  /send: #todo JL
    post:
      description:
      responses:
        '200':
          description: OK

  /ping:
    get:
      summary: Server heartbeat operation
      description: This operation is to know if the service is active
      responses:
        200:
          description: OK
          content: {}
        500:
          description: Error de servidor/servicio inactivo, validar con soporte cardif.
          content: {}
  /generate:
    post:
      tags:
      - Generate otp to send to the client.
      summary: Generate otp to validate purchase of client.
      description: |-
        <h1> Related projects
        * Digital sales
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/otpInputGeneration'
        required: false
      responses:
        200:
          description: Return
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/otpResponse'
        404:
          $ref: '#/components/schemas/otpResponse'
      x-codegen-request-body-name: otpInputGeneration
  /validate:
    post:
      tags:
      - Validate otp written by the client.
      summary: Validate OTP.
      description: |-
        <h1> Related projects
        * Digital sales
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/otpInputValidation'
        required: false
      responses:
        200:
          description: Return
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/otpValidationesponse'
        404:
          $ref: '#/components/schemas/otpValidationesponse'
      x-codegen-request-body-name: otpInputValidation
components:
  schemas:
    otpInputGeneration:
      type: object
      properties:
        partnerId:
          type: integer
          description: Partner Id
        cellphone:
          type: string
          description: Customer cellphone
        documnetType:
          type: string
          description: Customer documnetType
        documnetNumber:
          type: string
          description: Customer documnetNumber
        email:
          type: string
          description: Customer email
        channel:
          type: string
          description: Channel
    otpInputValidation:
      type: object
      properties:
        otpNumber:
          type: integer
          description: OTP number
        partnerId:
          type: string
          description: Partner Id
        cellphone:
          type: string
          description: Customer cellphone
        documnetType:
          type: string
          description: Customer documnetType
        documnetNumber:
          type: string
          description: Customer documnetNumber
        email:
          type: string
          description: Customer email
        channel:
          type: string
          description: ChanNel
    otpResponse:
      type: object
      properties:
        returnCode:
          type: integer
          description: codigo de retorno
        mesagge:
          type: string
          description: descripcion
        bodyResponse:
          type: object
          properties:
            otpNumber:
              type: integer
              description: numero otp
    otpValidationesponse:
      type: object
      properties:
        returnCode:
          type: integer
          description: codigo de retorno
        mesagge:
          type: string
          description: descripcion
        bodyResponse:
          type: object
          properties:
            null:
              type: object

